---
- name: cluster install
  hosts: web
  become: true
  roles:
    - pcs_start

- name: target install
  hosts: gfs
  become: true  
  roles:
    - target_start

- name: cluster prepare
  hosts: web
  become: true
  roles:
    - gfs2_start
