---
- hosts: all
  become: yes

  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: allow tcp
      ufw:
        rule: allow
        port: '80'
        proto: tcp
